name: docker-ci
on:
  push:
    branches:
      - main
    paths:
      - "**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Decide image tag
        id: vars
        run: |
          echo "TAG=0.1.${{ github.run_number }}" >>"$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max 
          tags: |
            ${{ env.REGISTRY }}/:${{ steps.vars.outputs.TAG }}
            ${{ env.REGISTRY }}/:latest